mysite/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<uuid:pk>/', views.DetailView.as_view(), name='detail'),
    path('new_question', views.CreateQuestion.as_view(), name='new_question'),
    path('<uuid:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<uuid:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime
import uuid

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    public = models.BooleanField(default=False)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.db.models import F

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now(),
            public=True
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class CreateQuestion(generic.CreateView):
    model = Question
    fields = ["question_text", "public"]
    template_name = "polls/new_question.html"
    
    def post(self, request):
        # get all keys starting with prefix "choice_"
        self.choices = [value[0] for key, value in dict(request.POST).items() if key.startswith("choice_")]
        
        return super().post(request)

    def form_valid(self, form):

        self.object = form.save()
        
        for choice in self.choices:
            obj = Choice(choice_text=choice, question=self.object)             
            obj.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('polls:detail', kwargs={'pk': self.object.pk})    

polls/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Polls</title>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css'
            %}">
    </head>
    <body>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% load static %}


{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />

<div class="detail-container">
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}

        <label class="container">{{ choice.choice_text }}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" 
                   value="{{ choice.id }}" type="checkbox">
            <span class="checkmark"></span>
        </label>

        {% endfor %}
        <input class="button" type="submit" value="Vote" />
        
        <div class="share-container">
            <input type="text" id="link" disbaled=true value="{{ request.META.HTTP_HOST }}{% url 'polls:detail' question.pk %}"/>
            <img class="icon" onclick="copyLink()" src="{% static 'polls/img/copy.png' %}"/>
        </div>

    </form>
</div>

<script>

    function copyLink() {
        var textElement = document.getElementById("link");
        textElement.select();

        document.execCommand("copy");

    }

</script>

{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% load static %}


{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />

{% if latest_question_list %}
    {% for question in latest_question_list %}
    
    <a href="{% url 'polls:detail' question.pk %}">
        <div class="question-card-container">
            <p>{{ question.question_text }}</p>
            <img class="icon" src="{% static 'polls/img/link.png' %}"/>
        </div>
    </a>
    {% endfor %}

{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="{% url 'polls:new_question' %}"><button class="button">Add Question</button></a>

{% endblock %}

polls/templates/polls/new_question.html
{% extends 'polls/base.html' %}

{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />

<form id="form" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="hidden"></input>
    <div>
        Choices:
        <div id="choice_list">

        </div>
    </div>

    <div class="new-choice-input-contaier">
        <input id="choice_input" type="text" place="choice name"></input>
        <img class="icon" src="{% static 'polls/img/plus.png' %}" id="add_choice"/>
    </div>

    <input class="button" type="submit" value="Create Question">
</form>

<script>

    var choices = [];

    var choiceButton = document.getElementById("add_choice")

    choiceButton.addEventListener("click", function() {

        /* Adds hidden choice input field to form */

        var choiceText = document.getElementById("choice_input");
    
        var choiceInputContainer = document.getElementById("choice_list");
        var formContainer = document.getElementById("form");

        var hiddenNode = document.createElement("input");
        hiddenNode.type = "hidden";
        hiddenNode.name = "choice_" + choices.length;
        hiddenNode.value = choiceText.value;

        var node = document.createElement("input");
        node.value = choiceText.value;
        node.type = "text";
        node.disabled = true;

        choiceInputContainer.appendChild(node);
        formContainer.appendChild(hiddenNode);
        choiceText.value = "";

        choices.push(choiceText.value);    
    });

</script>

{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}"><button class="button">Vote again?</button></a>

{% endblock %}